### ISSUE TITLE
feature: Create GitHub Action workflow for Go tests

### ISSUE THREAD

**Issue by raamsri** [stratastor/rodent#40]
# Feature Request

## Summary

Setup automated Go testing workflow for pkg/zfs directory

## Motivation

Explain why this feature is necessary and what problem it will solve.

### Sample Implementation

```
name: ZFS Package Tests

on:
  push:
    paths:
      - 'pkg/zfs/**'
  pull_request:
    paths:
      - 'pkg/zfs/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: true
      
      - name: Install ZFS
        run: |
          sudo apt-get update
          sudo apt-get install -y zfsutils-linux
          # Well, this has to be zfs-2.3.0. The current rc-4 release requires manual compile from source.

      - name: Install NFS
      - name: Install Samba
      - name: Other dependencies? 

      - name: Run Tests
        run: |
          cd pkg/zfs
          go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./pkg/zfs/coverage.txt
          flags: zfs-tests
```

## Acceptance Criteria
- [ ] Automated test runs on pkg/zfs changes
- [ ] Go dependency caching?
- [ ] ZFS utilities available in test environment
- [ ] All dependencies like NFS, Samba must be fulfilled.
- [ ] Ability to create Ubuntu users/groups in the virtual setup
- [ ] Run commands with sudo privileges
- [ ] Required utils and setup to allow command executions to meet the test suite requirements
- [ ] Test coverage reporting
- [ ] Proper error notifications

## Additional Context
Requires repository secrets setup for codecov integration
